### ISSUE TITLE
Linux/Macos port

### ISSUE THREAD

**Issue by CedricGuillemet** [CedricGuillemet/Imogen#31]
Everything is coded with multiplatform in mind (mostly). And I compiled the project on a virtualized Ubuntu. It was a couple months ago and a Linux port (a solid one) would be great.
Kudos if there is a possibility to produce binaries(packages) from a bot.

**Comment by mattrei** [comment]
yes please that would be great to have a guid for linux or even compiled binaries!

**Comment by CedricGuillemet** [comment]
I still have hope to find a contributor for the Mac/Linux port :)

**Comment by highway900** [comment]
Amazing Project @CedricGuillemet I have just started playing with building in a ubuntu:18.04 docker container. Which version of Ubuntu did you use to compile against?

I would be happy to follow through with build bot if you can share some build specifics with me.

(note: I am not the greatest C++ person)

**Comment by CedricGuillemet** [comment]
Hi
Thank you for putting some time in the project :)
I tried with a Centos 7 virtual machine (a long time ago).
Most of the effort I put was in the cmake file. It needs a couple packages: libSDL-dev, opengl,... 
Since that test I may have added some non cross platform. Let me know if that happens, I'll fix that quickly.

**Comment by highway900** [comment]
So I am back.
I have setup a build pipeline using azure pipeline. This is pretty fast and free for open source applications. It also supports Windows, OSX and Linux which is nice, cos no one really support OSX.

https://dev.azure.com/highway900/Imogen/_build/results?buildId=4

That is the build result with a fairly vanilla cut of master. The only change is setting the C++ standard to 17. This fixed numerous build errors like using auto.

The current errors can be fixed by including `math.h` but I assume that this is done some other way with VS? This is pretty interesting to me, cpp build systems are not my strong suite.

I can invite you to the azure project, or you could start one for the project. I just thought it might be an easy way to run the builds and create some release/build artifacts for many platforms automatically.

Cheers.

**Comment by CedricGuillemet** [comment]
That looks nice! Is there a way to not create a repo on azure but use github instead?

**Comment by highway900** [comment]
The azure build system just points at my github fork of Imogen :) So there is no azure repository that I know of. I did allow access to azure to my fork.
You can also manage the configuration yml file from inside the github repo.

**Comment by highway900** [comment]
As far as I can tell the version of `pyconfig.h` is generated by python configure system (or copied from `PC/pyconfig.h`) in the cpython source. The version included in imogen is for VS c++ or wacom compiler specifically. The file is ignored in the cpython [source](https://github.com/python/cpython/blob/1f24a719e7be5e49b876a5dc7daf21d01ee69faa/.gitignore#L95)

I will try to compile with the linux python3.7-dev package instead.

**Comment by highway900** [comment]
Compiling with an installed version of python3.7 and package lookup in CMakeLists fixed the python dependency.

Now the compiler semantics are appearing. I get a different set of errors for GCC and Clang. I will focus on Clang at the moment in the hope that translates to OSX easier. Changing the C++ standard  (11, 14, 17) also generates a variety of different errors. I am currently using 14 as 17 causes errors with pybind, which fits VS the best?

**Comment by CedricGuillemet** [comment]
I don't know. I use vs2017 default settings. Focusing on Clang is a good idea.

**Comment by axredneck** [comment]
I just tried to build current "dev-0.14" branch and got this error:
`/home/redneck/programs/Imogen/src/EvaluationContext.cpp:26:10: fatal error: SDL.h: No such file or directory`
` #include <SDL.h>`
though i have this file (`/usr/include/SDL/SDL.h`).
Arch Linux.

**Comment by highway900** [comment]
The path for SDL is likely incorrect in the include.

‘#include <SDL/SDL.h>’

This is actually where ‘SDL.h’ is. I would suggest changing the cmakelists
file to search in the include subdirectory.

**Comment by axredneck** [comment]
Trying to compile dev-0.14 branch:
`/home/redneck/programs/Imogen/src/Platform.h:101:2: error: #error unknown platform`
` #error unknown platform`

**Comment by CedricGuillemet** [comment]
What's your compiler/OS? The platform.h sets the configuration and enables features based on the target. Currently, only Windows thru MSVC and emscripten are supported.

**Comment by axredneck** [comment]
@CedricGuillemet Arch Linux as before, GCC 8.3.0

**Comment by unfa** [comment]
Hey! Are you looking for help with the Linux port?
I'm a graphic designer and I'm really excited to see Imogen being a thing, as I want to make generative PBR materials, but I don't want to become Adobe's servant for this.

I'd be really excited to help you develope the Linux port (the web build doens't seem to work well for me).

I'm running Ryzen 7 1700 / GTX 1060 6GB / 32GB RAM and Manjaro Linux.

**Comment by unfa** [comment]
I've truied building the newest git code on Linux, as well as the latest release. No success so far.

Building the latest release I git this error:

```
/data/Applications/Imogen-0.13.0/ext/python37/include/pyconfig.h:59:10: fatal error: io.h: No such file or directory
 #include <io.h>
          ^~~~~~
compilation terminated.
```

**Comment by unfa** [comment]
> `/`

I have the same problem.

**Comment by unfa** [comment]
> Trying to compile dev-0.14 branch:
> `/home/redneck/programs/Imogen/src/Platform.h:101:2: error: #error unknown platform`
> ` #error unknown platform`

I have the same issue.
#68

**Comment by CedricGuillemet** [comment]
Yes, I broke the linux build with emscripten. Fixing it now.

**Comment by nafergo** [comment]
Any plans for appimage releases?

**Comment by axredneck** [comment]
@nafergo any plans for compile from sources first, the rest later.

**Comment by axredneck** [comment]
Now it compiles but crashes:
```
Imogen: /home/redneck/programs/Imogen/ext/imgui_draw.cpp:1623: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `0' failed.
```

**Comment by CedricGuillemet** [comment]
It crashes because it doesn't find the font file. In your terminal run the app from the bin directory

**Comment by axredneck** [comment]
Thank You, it works!

**Comment by axredneck** [comment]
Doesn't compile again
```
CMake Error at ext/bgfx/cmake/3rdparty/glsl-optimizer.cmake:55 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  ext/bgfx/cmake/tools/shaderc.cmake:14 (include)
  ext/bgfx/cmake/tools.cmake:17 (include)
  ext/bgfx/CMakeLists.txt:61 (include)
```
Arch Linux, Imogen dev-0.14 branch.

**Comment by leiserfg** [comment]
Try updating the submodules.

**Comment by axredneck** [comment]
> Try updating the submodules

Already tried with no success.

**Comment by leiserfg** [comment]
Apparently, something is broken with bgfx, because I updated the submodules and now is failing for me also.

**Comment by leiserfg** [comment]
The error I'm getting is because of this change in bgfx
https://github.com/bkaradzic/bgfx/commit/855623e1534e9114847d8df3c2be52cb348e6493

**Comment by leiserfg** [comment]
I'm not sure (I didn't read all the imogen code) but maybe will be healthier to use Vulkan directly, cause bgfx is doing api changes.  You can use vukan on linux and windows and MolteVk or similar on macos.

**Comment by CedricGuillemet** [comment]
I can't reproduce the issue with cmakegui + msvc :(

**Comment by leiserfg** [comment]
It happens if you update the submodules recursively cause they are making changes on bgfx, check 

bkaradzic/bgfx@855623e

**Comment by leiserfg** [comment]
Can be fixed just by replacing `VertexDecl`  with `VertexLayout`.

**Comment by leiserfg** [comment]
But then I started to get more bgfx errors, updating the submodules was a bad idea.

**Comment by CedricGuillemet** [comment]
I've pushed an update. let if know if it solves something

**Comment by axredneck** [comment]
I did `git pull origin dev-0.14` and `git submodule update`, still the same issue:
```
CMake Error at ext/bgfx/cmake/3rdparty/glsl-optimizer.cmake:55 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
```
